### Quick review of numpy module : random

[ref](https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html)

In [1]:
import numpy as np

### 1. `np.random.rand(shape)`

균일 분포에서 0 ~ 1 사이의 난수를 추출해 파라미터 모양의 array를 반환한다.

* Parameter : create an array of the given shape
* Retunrs : n dimensions array (random value)
* Range : 0 ~ 1, 균일한 분포

In [5]:
np.random.rand(3,2)

array([[0.98376019, 0.51313347],
       [0.17487952, 0.14111812],
       [0.57574274, 0.94235639]])

In [4]:
np.random.random_sample()

0.16255496273187608

### 2. `np.random.randn()`

가우시안 균일정규분포 (Gqussian standard normal distribution) 에서 0 ~ 1 사이의 난수를 추출해 파라미터 모양의 array를 반환한다.  

- Parameters : (optional) create a array of the given shape, should be all positive
    - if no parameter is given, Float is returned
- Returns : n dimentions array
- Range : 0 ~ 1


=> `np.random.standard_normal` : (Similar) takes tuple as the first argument

- Parameters : (optional: default is None) size = (m, n, k)


In [6]:
np.random.randn()

-0.8261774041686861

In [7]:
np.random.randn(2, 5)

array([[ 1.19658983, -0.50348263, -1.25472469,  0.49492173, -0.3854837 ],
       [-0.13238452, -2.2324582 ,  0.30573541,  1.35772937, -0.64210552]])

In [9]:
# 왜 이렇게 되는지 모르겠지만
# N(3, 6.25) 분포에서 난수를 추출하여 2 x 4 모양의 행렬을 만든다.

2.5 * np.random.randn(2,4) + 3

array([[-0.82924676,  3.04819117,  3.42960009,  2.42082596],
       [ 1.79016981,  3.81474596,  2.1174638 ,  1.83481301]])

In [14]:
t = np.random.standard_normal(10)  # 파라미터의 개수만큼 난수 출력 (1행 10열 행렬)
print(t)
print(t.shape)

[ 0.55719666 -0.14390836  0.64013184  0.56234085 -1.80549922  1.22531208
 -0.13294471 -0.49953921  0.21600127 -0.41485064]
(10,)


In [13]:
s = np.random.standard_normal(size = (3, 4, 2))
print(s)
print(s.shape)

[[[-0.55624044 -0.49651196]
  [-1.93798424  0.26655166]
  [-1.35764099  0.85172791]
  [-0.28357598 -0.91537844]]

 [[-0.16020178 -0.87972331]
  [-1.23728201 -1.42981558]
  [-0.31563566  0.37734967]
  [-0.21092091 -0.72128748]]

 [[-1.72757816  0.12342448]
  [-0.53703913  0.51736023]
  [ 0.42194747 -0.50500025]
  [-0.14920294  0.85659114]]]
(3, 4, 2)


### 3. `randint(low[, high, size, dtype])`

이산 균등분포 (discrete uniform) 에서 범위를 지정해 값을 추출한다.  
이 때, 범위는 [low, high) 의 반열린구간이며 최대값을 지정하지 않을 경우 유일 파라미터가 최대값이 된다.

- Parameters
    - low : int
    - high : int
    - size : int or tuple (m, n, k) 
    - dtype : int64, int, ... ...
- Returns : int or ndarray of **ints**

In [15]:
np.random.randint(2, size = 10)

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 1])

In [16]:
np.random.randint(2, 10, size = (2, 4, 6))

array([[[6, 8, 4, 2, 5, 9],
        [6, 9, 6, 3, 3, 8],
        [3, 8, 8, 2, 4, 7],
        [6, 9, 3, 6, 2, 9]],

       [[3, 4, 7, 5, 3, 3],
        [9, 9, 4, 9, 6, 2],
        [6, 5, 7, 3, 9, 3],
        [2, 3, 6, 5, 7, 7]]])